---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  STORAGE_NAMES:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  BOSH_VM_FOLDER:
  BOSH_TEMPLATE_FOLDER:
  BOSH_DISK_PATH:
  ICMP_CHECKS_ENABLED:
  NSX_MANAGER_ADDRESS:
  NSX_MANAGER_FQDN:
  NSX_MANAGER_ADMIN_USER:
  NSX_MANAGER_ADMIN_PASSWD:
  INFRA_NETWORK_NAME:
  INFRA_VCENTER_NETWORK:
  INFRA_NW_CIDR:
  INFRA_EXCLUDED_RANGE:
  INFRA_NW_DNS:
  INFRA_NW_GATEWAY:
  INFRA_NW_AZ:
  DEPLOYMENT_NETWORK_NAME:
  DEPLOYMENT_VCENTER_NETWORK:
  DEPLOYMENT_NW_CIDR:
  DEPLOYMENT_EXCLUDED_RANGE:
  DEPLOYMENT_NW_DNS:
  DEPLOYMENT_NW_GATEWAY:
  DEPLOYMENT_NW_AZ:
  SERVICES_NETWORK_NAME:
  SERVICES_VCENTER_NETWORK:
  SERVICES_NW_CIDR:
  SERVICES_EXCLUDED_RANGE:
  SERVICES_NW_DNS:
  SERVICES_NW_GATEWAY:
  SERVICES_NW_AZ:
  DYNAMIC_SERVICES_NETWORK_NAME:
  DYNAMIC_SERVICES_VCENTER_NETWORK:
  DYNAMIC_SERVICES_NW_CIDR:
  DYNAMIC_SERVICES_EXCLUDED_RANGE:
  DYNAMIC_SERVICES_NW_DNS:
  DYNAMIC_SERVICES_NW_GATEWAY:
  DYNAMIC_SERVICES_NW_AZ:
  AZ_1:
  AZ_1_CUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_2:
  AZ_2_CUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_3:
  AZ_3_CUSTER_NAME:
  AZ_3_RP_NAME:
  NTP_SERVER_IPS:
  OPS_DIR_HOSTNAME:
  NSX_EDGE_GEN_NAME:
  ISOZONE_SWITCH_NAME_1:
  ISOZONE_SWITCH_CIDR_1:    
  ISOZONE_SWITCH_1_NETWORK_NAME:
  ISOZONE_SWITCH_1_VCENTER_NETWORK:
  ISOZONE_SWITCH_1_EXCLUDED_RANGE: 
  ISOZONE_SWITCH_1_NW_DNS: 
  ISOZONE_SWITCH_1_NW_GATEWAY:
  ISOZONE_SWITCH_1_NW_AZ:

inputs:
  - name: concourse-vsphere
  - name: om-cli
  - name: nsx-gen-output

run:
  path: concourse-vsphere/tasks/config-opsdir/task.sh
