---

platform: linux

image_resource:
  type: docker-image
  source: {repository: virtmerlin/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZ_RABBIT_SINGLETON:
  TILE_AZS_RABBIT:
  TILE_RABBIT_PROXY_IPS:
  TILE_RABBIT_PROXY_VIP:
  TILE_RABBIT_ADMIN_USER:
  TILE_RABBIT_ADMIN_PASSWD:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-rabbit/task.sh
