---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  PRODUCT_NAME:
  REPLICATOR_NAME:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  TILE_AZS_ISO:
  TILE_AZ_ISO_SINGLETON:
  NETWORK_NAME:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
  SSL_TERMINATION_POINT:
  SSL_CERT:
  SSL_PRIVATE_KEY:
  ROUTER_SSL_CIPHERS:
  ROUTER_STATIC_IPS:
  CELL_DISK_CAPACITY:
  CELL_MEMORY_CAPACITY:
  APPLICATION_NETWORK_CIDR:
  APPLICATION_NETWORK_MTU:
  INSECURE_DOCKER_REGISTRY_LIST:
  SEGMENT_NAME:
  IS_ROUTER_INSTANCES:
  IS_TCP_ROUTER_INSTANCES:
  IS_DIEGO_CELL_INSTANCES:
  TILE_ISO_ENABLE_C2C:
  TILE_ISO_C2C_NETWORK_CIDR:
  TILE_ISO_C2C_VTEP_PORT:
  TILE_ISO_ISOLATED_ROUTER_SECURITY_GROUP:
  TILE_ISO_ISOLATED_TCP_ROUTER_SECURITY_GROUP: 

inputs:
  - name: concourse-vsphere
  - name: om-cli
  - name: nsx-gen-output

run:
  path: concourse-vsphere/tasks/config-replicated-is-tile/task.sh
